# ????????
# ??????
logging.level.com.pn=DEBUG
logging.level.org.springframework.web=DEBUG

# ?????SQL??
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ?????
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true